apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'backend'
        static_configs:
          - targets: ['food-backend:5000']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-prometheus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-prometheus
  template:
    metadata:
      labels:
        app: food-prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: food-prometheus
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: food-prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-grafana
  template:
    metadata:
      labels:
        app: food-grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: food-grafana
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3000
  selector:
    app: food-grafana
